baseURL = "http://example.org/"
languageCode = "en-us"
title = "EC2 Spot Workshops"
theme = "learn"
uglyurls = true
sectionPagesMenu = "main"
pygmentsCodeFences = true


[blackfriday]
hrefTargetBlank = true

[params]
themeVariant = "mine"
showVisitedLinks = false
description = "EC2 Spot Workshops"
disableSearch = false
disableAssetsBusting = false
disableLanguageSwitchingButton = true
disableShortcutsTitle=true


[[menu.shortcuts]] 
name = "<i class='fab fa-github'></i> Github repo"
identifier = "github"
url = "https://github.com/awslabs/ec2-spot-labs/tree/master/workshops/ec2-spot-fleet-web-app"
weight = 1


[[menu.shortcuts]]
name = "<i class='fas fa-bullhorn'></i> Credits"
identifier = "credits"
url = "https://github.com/schmutze"
weight = 22

[outputs]
home = [ "HTML", "AMP", "RSS", "JSON"]
page = [ "HTML", "AMP"]


[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false
