version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/koel
  - source: ./koel.conf
    destination: /etc/httpd/conf.d
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/build_and_install.sh
      timeout: 300
      runas: root
    - location: scripts/configure_httpd_php.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/configure_db.sh
      timeout: 300
      runas: root
    - location: scripts/start_services.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_services.sh
      timeout: 300
      runas: root